# Generated by Django 4.2 on 2023-04-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=9)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=4)),
                ('complemento', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField()),
                ('telefone', models.CharField()),
                ('area', models.CharField(choices=[('Atendimento', 'Atendimento'), ('Cozinha', 'Cozinha'), ('Gerencia', 'Gerencia'), ('Pagamento', 'Pagamento')])),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='restaurante.endereco')),
            ],
        ),
    ]
